name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

# Backend Job
  backend:
    name: Build and Push Backend to DockerHub
    runs-on: ubuntu-latest

    steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Set up Docker
            uses: docker/setup-buildx-action@v2
          - name: Log in to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build the Docker image
            run: | 
              docker build -t onovikov/justintime_api:latest -f ./justintime-api/Dockerfile ./justintime-api
              docker push onovikov/justintime_api:latest
# Frontend Job
  frontend:
    name: Build and Push Frontend to DockerHub
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and Push Frontend Image
          run: |
            docker build --build-arg VITE_BACKEND_URL=${{ secrets.BACKEND_URL }} -t onovikov/justintime_fe:latest -f ./justintime-fe/Dockerfile ./justintime-fe
            docker push onovikov/justintime_fe:latest